# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: The Lotus Vibes
email: hello@thelotusvibes.com
description: Journey to mindfulness and happiness, inspired by timeless Buddhist wisdom.
keywords: Buddhism, Buddhist, graphic design, artwork, design, mindfulness, Buddhism art, Buddhism design, positivity, happiness
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://www.thelotusvibes.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter:
  username: thelotusvibes
facebook:
  publisher: 1341185725912969

logo: /assets/img/thelotusvibes-logo.svg

social:
  name: Ada Chiu
  links:
    - https://twitter.com/thelotusvibes
    - https://www.facebook.com/thelotusvibes

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-96037581-4

# Build settings
markdown: kramdown
gems:
  - jekyll-seo-tag
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
